### ISSUE TITLE
Mod 04 Lab - Creating Azure AD Connect Attribute Filter fails

### ISSUE THREAD

**Issue by itbland** [MicrosoftLearning/20347-Enabling-and-Managing-Office365#46]
In Mod 04 Lab, Exercise 2, Task 4, on the step:

- **To save the rule, click Add, and then close Synchronization Rules Editor window.**

The **Sync Rules Editor** throws the following error:

> Object reference not set to an instance of an object.

I suspect that the current version of AD Connect may have a flaw causing the error (and it will be corrected shortly with an update) or possibly there is something wrong with the LON-DS1 image getting a little too out of date.

**Comment by JasonHershey** [comment]
I ran through it with a problem on my own vms. I've re-downloaded the VMs for the class to see if its specific to them. I should have that done shortly.

**Comment by daisuketanabe** [comment]
I came across this problem today, this is happing not only on LOD labs, but others, too. I had to improvise to work around this issue.

Instead of adding a new rule, clone one of the existing one (I used 'In from AD - user Join' rule, but it can be any rule) by clicking 'Edit'. Since this is a built-in rule, It will ask you to create a copy or edit, click 'Yes' to create a copy. And then use this cloned rule to create a sync rule according to lab instruction. Don't forget to re-enable the original rule. When you create a copy from the built-in rule, it will disable the original rule. So click 'Edit' the original rule, and make sure to untick 'Disabled' box.

These steps worked for me. I don't know what was the cause of problem, but it seems like issue with new AD Connector.

**Comment by itbland** [comment]
Fantastic!, thanks for the work-around (I didn’t think of that—I just assumed MS would fix the new version before class this week)

**Comment by JasonHershey** [comment]
fyi, I confirmed this is not just a labs issue or issue with these VMs. I verified using standard VMs and my own environment.  checking on how to push the bug to MS

**Comment by JasonHershey** [comment]
Checked with the course designers.  I've added a note to the high level instructions and provided an alternative procedure to the LAK based on @daisuketanabe suggested workaround.  I'm also working on routing the bug to the right team at MS.

**Comment by itbland** [comment]
Update: I ran this lab today in class and was able to create a new rule normally.
AD Connect version 1.1.614.0, released 9/5/2017 (the current download)
[Azure AD Connect: Version release history](https://docs.microsoft.com/en-us/azure/active-directory/connect/active-directory-aadconnect-version-history)
