### ISSUE TITLE
Lab step question, Mod 04 Ex 3 Task 1

### ISSUE THREAD

**Issue by itbland** [MicrosoftLearning/20347-Enabling-and-Managing-Office365#7]
In Mod 04, Ex 3, Task 1, at Step 3 (at least it will be step 3 if the corrections ever get merged) 

> Select Password never expires.

--Why would we set Perry Brill's password to never expire in the domain? It is not a real-world setting and may give the student the incorrect impression that they MUST do it. I think this step should be removed.

**Comment by JasonHershey** [comment]
The setting is not necessary, for sure. Not sure I would say its not real world.  Not best practice, definitely, but I know quite a few companies where they don't want to change passwords. Mostly small businesses, and a few were there are 1 or 2 executives that don't want to change THEIR passwords. :-).  But, since its not necessary and it might make someone think it is common/required, lets remove it.  (done)
